### ISSUE TITLE
Pager-api expecting kaminari despite config

### ISSUE THREAD

**Issue by ntaylor89** [IcaliaLabs/pager-api#11]
Hi there! I'm trying to get this gem working, but am having difficulty getting it to work with `will_paginate`.

I'm using rails 4.2.7.1, will_paginate-3.1.0. My PagerApi Initializer looks like this:

```rb
PagerApi.setup do |config|
  config.pagination_handler = :will_paginate
end
```

__My Problem__:
When I try to call `paginate(....)` from a controller I get `undefined method 'per'...`.

It appears that, despite my config, pager-api is trying to use kaminari. If I pry right before my pagination call and look at `show-method paginate`, I see...
`Owner: PagerApi::Pagination::Kaminari`

However `PagerApi.pagination_handler` returns `:will_paginate`

After some local testing it appears that the initializer is not being loaded before line 2 of `hooks.rb` is executed, so the gem defaults to using the kamari handler. This bombs because I don't have kaminari installed.

__Possible Solution:__
Looking at the rails documentation, I think the existing railtie is being called before the setup block is called. If I'm missing something obvious, please let me know. 

I was able to get this working by changing `railtie.rb` to look like:

```rb
Module PagerApi
  class Railtie < Rails::Railtie
    config.after_initialize do
      require 'pager_api/hooks'
    end
  end
end
```

**Comment by kurenn** [comment]
Looks good, would you be kind to place a pull request so the credit is yours? Thanks!

**Comment by ntaylor89** [comment]
Can do! I'll try to get that up in the next day or two.

**Comment by kurenn** [comment]
Sweet!

**Comment by kurenn** [comment]
I'm closing this, it was merged already, thanks @ntaylor89
