### ISSUE TITLE
[Solved] undefined method 'paginate'

### ISSUE THREAD

**Issue by blimey85** [IcaliaLabs/pager-api#17]
I had the problem that a few others have had with the undefined paginate method. I'm using Rails 5.1.2 and have a regular Rails app, rather than one that's just an API. I set everything up per the documentation using Kaminari and couldn't get it to work. Tried another gem and it mentioned that for Rails 5+ you needed to add an include line. I then looked in this gem and added the following to my applicaton_controller.rb:

`include PagerApi::Pagination::Kaminari`

Now everything works as expected. I saw in the code where this should be getting included automatically but that's apparently not happening, so this fixes it. I thought I would post this in case anyone else runs into this issue.

**Comment by kurenn** [comment]
Thanks, I'll dig into the problem and see if I can fix it to make it work with Rails 5 without doing this, maybe on the initializer?...

Please don't hesitate on placing a PR if you find out where the fix should be

**Comment by nik736** [comment]
@blimey85 This only seems to work in development mode. Is there any way to get this to work in production?

**Comment by kurenn** [comment]
What problem are you having?

**Comment by nik736** [comment]
Unable to load application: NameError: uninitialized constant PagerApi::Pagination

**Comment by kurenn** [comment]
But works on development?

**Comment by nik736** [comment]
Yep, only in test/production there are problems. 

I made a workaround now by implementing the file directly in my app folder.

**Comment by kurenn** [comment]
Which file?
