### ISSUE TITLE
Support for Pagy

### ISSUE THREAD

**Issue by cseelus** [IcaliaLabs/pager-api#22]
[Pagy](https://github.com/ddnexus/pagy) is a relatively new "pagination gem that outperforms the others in each and every benchmark and comparison".

Would this paginator be something Pager API could support?

**Comment by kurenn** [comment]
That would be interesting, did not know the existance of this gem, but I can give it a try and start working on it, thanks for the suggestion!

**Comment by kurenn** [comment]
I started to work on this, I was testing pagy first, I'll let you know the PR number

**Comment by ddnexus** [comment]
Hi @kurenn, let me know if I can help in any way. Thanks.

**Comment by kurenn** [comment]
Here it is! - https://github.com/IcaliaLabs/pager-api/pull/23 - please let me know how it goes!

**Comment by kurenn** [comment]
Closed by #23
