### ISSUE TITLE
issue with nested associations

### ISSUE THREAD

**Issue by sumit-rvtech** [IcaliaLabs/pager-api#27]
render json: @posts, include: ['author', 'comments', 'comments.author']

How could I use the above statement with the below line:

paginate @posts, per_page: 15

I am not able to add the nested associated objects. please suggest.

**Comment by kurenn** [comment]
Which gem are you using to serialize?

**Comment by sumit-rvtech** [comment]
Hey, I finally got the answer for that with this serializer

ActiveModelSerializers.config.default_includes = '**'

I just added this line in serializer initializer. By the way thanks for the help.

**Comment by kurenn** [comment]
Sure!, Hope you find the gem useful! please let me know how can I help!
