### ISSUE TITLE
0.2.3 release has broken pagination header behaviour

### ISSUE THREAD

**Issue by bentheax** [IcaliaLabs/pager-api#30]
Hello :wave:

It looks as though version 0.2.3 released on Rubygems returns the total number of _pages_ as `X-Total-Count`. Code in master looks OK, so I presume the 0.2.3 release has a since-fixed bug. I can't verify, as there are no tags for releases.

Suggested resolution would be:

1. Fix typo on [this line of the config file](https://github.com/IcaliaLabs/pager-api/blob/master/lib/pager_api.rb#L17)
2. Tag and release a new version to Rubygems

**Comment by kurenn** [comment]
Thanks, let me review and make the change!

**Comment by kurenn** [comment]
Solved with 9595f1d38a116860944aea39b98d2ae3eaef24cb

I'm closing this! Thanks for reporting it!
