### ISSUE TITLE
undefined method `paginate'

### ISSUE THREAD

**Issue by BrahimDahmani** [IcaliaLabs/pager-api#6]
after install and configure PagerApi & Kaminari, i got `#<NoMethodError: undefined method 'paginate' for #<V1::ProjectsController:0x005563f62bff70>>`

### env :
  * rails 5.0.0.1
  * kaminari 0.17.0
  * PagerApi 0.1.1

**Comment by kurenn** [comment]
Can I take a look at your code when calling the paginate method

**Comment by BrahimDahmani** [comment]
```ruby

  def index
    paginate Project.all
  end

```

Actually i can pass this by including manually `PagerApi::Pagination::Kaminari` in the `V1::ProjectsController`


after that i have the same issue as #4

**Comment by ccoeder** [comment]
Its not working for me too.

```
  # GET /members
  def index
    paginate Member.all, per_page: 15
  end
```

**Comment by BrahimDahmani** [comment]
@ccoeder i solved this issue in this PR #7 

you can use the gem from [my fork](https://github.com/BrahimDahmani/pager-api) or wait until the PR merge

**Comment by ccoeder** [comment]
@BrahimDahmani sorry but im a little bit newbie, how can i use your gem?

**Comment by BrahimDahmani** [comment]
add to you `Gemfile`
```ruby
gem 'pager_api' , :github => 'BrahimDahmani/pager-api'
```

**Comment by ccoeder** [comment]
@BrahimDahmani yes this one is working but you have to specify branch, any way thanks!

**Comment by PAMulligan** [comment]
I am running into this issue as well, my index action looks like this:

    def index
        paginate Contact.where.not(isdeleted: true)
    end

I'm using Rails 4.2.6, Kaminari and Pager_Api

**Comment by ccoeder** [comment]
@PAMulligan If you still can not figure it out go to the gemfile and add the following lines

`
gem 'pager_api' , :github => 'BrahimDahmani/pager-api', :branch => "bugfixes"`

**Comment by PAMulligan** [comment]
I tried that yesterday, same error message

**Comment by PAMulligan** [comment]
However, I just tried it today, and it seems to be working, thank you!

**Comment by kurenn** [comment]
@BrahimDahmani I will take a look and test your code! seems good so far!

**Comment by kurenn** [comment]
It has been merge, please check the documentation on how to customize and play with active model serializers!

**Comment by wuliwong** [comment]
I have this error and added the config for  active model serializers 0.10. I have switched to a different gem but I was wondering if you have to have your controller inherit from `ActionController::API` to make the `paginate` method available? I wasn't doing that when I was working with this gem and I suspect that may have been the source of my problem.
