### ISSUE TITLE
Conflict with serializer

### ISSUE THREAD

**Issue by PAMulligan** [IcaliaLabs/pager-api#8]
I have kind of a two-fold issue. I'm running the bug-fixes branch that has been mentioned in two other threads here, and it's working, but not the way I'd like it to. In the initializer, I set include_pagination_on_meta to false, because I only want the link headers. However, when using Postman to run my index action, I indeed get the meta information in the body. This also invalidates the serializer I had set up, and shows every attribute of the given records. I assume if I can make the meta data disappear, the serializer will return to normal, so I would like to fix that first. Any idea what is causing this?

**Comment by kurenn** [comment]
I'm not sure what is causing that, are you using Rails 5 with the `api` option? I will have more time to resolve this kind of things! thanks to the holidays! so any more information is more than welcome!

**Comment by PAMulligan** [comment]
No, I'm using 4.2.6 with the rails-api gem. Thank you for the support!

**Comment by PAMulligan** [comment]
I added the initializer line

    ActiveModelSerializers.config.adapter = :json_api

but I'm still seeing the meta data, instead of just showing up in the headers. As before, it's showing all of the columns in the JSON response, not just the ones that I indicate in the serializer.

**Comment by kurenn** [comment]
Can you please update the gem to `0.2.1`, I just upload changes from @BrahimDahmani.

Tell me how it goes!

**Comment by PAMulligan** [comment]
That works, thank you so much!

**Comment by kurenn** [comment]
You are welcome!
