### ISSUE TITLE
Remove "data" and "links" from JSON response

### ISSUE THREAD

**Issue by PAMulligan** [IcaliaLabs/pager-api#9]
Pager-api is really useful, thank you for making it! I have one tiny issue that I can't figure out. I only want the pagination data in the headers, which works fine, but I'd like to purge a couple of things from my JSON response. When I do an index action, for instance, my response looks something like this:

    {
        "data": [
            {
                "id": ...
            }
        ],
        "links": {}
    }

I would like to remove the first and last, and just have it look like my responses looked before adding pager-api, i.e.

    {
        "id": "29jf9s",
        "name": "etc. etc."
        ...
    }

I'm using active-model-serializers 0.10, if that's relevant as well.

EDIT

My index action looks like this:

    def index
        paginate SubOrder.unscoped
    end

And my serializer looks like this:

    class SubOrderSerializer < ActiveModel::Serializer
        attributes :id, :num_pages, :cost, :url, :date_created, :date_fulfilled
    end

**Comment by kurenn** [comment]
Can I see the index action and the serializer you are using?

**Comment by kurenn** [comment]
Was this solved?...can you provide any info on why this was closed?

**Comment by PAMulligan** [comment]
It wasn't solved, so much as it's not a problem with my company's specification, they are okay with the "data" and "links" attributes being listed.

**Comment by kurenn** [comment]
I think the solution was to actually to change the adapter to `:json`, checkout the official documentation at [https://github.com/rails-api/active_model_serializers#high-level-behavior](https://github.com/rails-api/active_model_serializers#high-level-behavior) and specifically this line:

```ruby
ActiveModelSerializers.config.adapter = :json_api
```

Just include it on a initializers if you are on Rails....

**Comment by PAMulligan** [comment]
Yes, that was already set in the initializer.
